/** Mapa de Vektor. Lo escribe el editor (/editor/); el formato, en src/maps/formato.js. */
export default {
  clave: "largoYPuerta",
  label: "Largo y Puerta",
  card: {"trains":"Sostener y cruzar un carril largo, pre-apuntar un paso obligado y pasar de largo a corto en la misma sesión.","risk":"El más cargado de geometría: hay mucho que leer antes de moverse con soltura.","replay":"Alta. Tres zonas que se pueden entrenar por separado."},
  room: {"width":40,"depth":40,"height":10},
  spawn: {"x":0,"z":17.5},
  boxes: [
    {"x":-8,"z":-10.5,"w":1.2,"d":9,"kind":"alta"},
    {"x":-8,"z":0.5,"w":1.2,"d":10.5,"kind":"alta"},
    {"x":-7,"z":15.2,"w":14,"d":1,"kind":"media"},
    {"x":-18,"z":3,"w":4.5,"d":2,"kind":"media"},
    {"x":-14,"z":-4,"w":4.5,"d":2,"kind":"media"},
    {"x":-15,"z":-10,"w":4.5,"d":2,"kind":"media"},
    {"x":-1,"z":-5,"w":3,"d":1.5,"kind":"media"},
    {"x":-4,"z":1,"w":3,"d":1.5,"kind":"media"},
    {"x":-5,"z":8,"w":3,"d":3,"kind":"baja"},
    {"x":2,"z":2.5,"w":3,"d":3,"kind":"baja"},
    {"x":11,"z":4.5,"w":3,"d":3,"kind":"baja"},
    {"x":15,"z":0.5,"w":3,"d":3,"kind":"baja"},
    {"x":0,"z":4.5,"w":3.5,"d":2,"kind":"bordillo"},
    {"x":4.5,"z":8.5,"w":3.5,"d":2,"kind":"bordillo"},
    {"x":6.5,"z":1.5,"w":1.5,"d":5,"kind":"alta"},
    {"x":2,"z":-7,"w":4,"d":2,"kind":"media"},
    {"x":-19,"z":-19,"w":38,"d":7,"kind":"plataforma"},
    {"x":-16,"z":-13.2,"w":2.5,"d":1.2,"kind":"parapeto","base":"plataforma"},
    {"x":-9.5,"z":-13.2,"w":3,"d":1.2,"kind":"parapeto","base":"plataforma"},
    {"x":-2.5,"z":-13.2,"w":18.5,"d":1.2,"kind":"parapeto","base":"plataforma"},
  ],
  ramps: [
    {"x":16,"z":-12,"w":3,"d":6,"fromZ":-6,"toZ":-12,"top":"plataforma"},
    {"x":-19,"z":-12,"w":3,"d":6,"fromZ":-6,"toZ":-12,"top":"plataforma"},
  ],
  spawnZone: [
    {"x":-20,"z":15.2,"w":40,"d":4.8},
  ],
  objectiveSites: [
    {"id":"largo-fondo","x":-13,"y":0,"z":-11,"zone":"El Largo"},
    {"id":"balcon","x":-12,"y":"plataforma","z":-16.5,"zone":"El Balcón"},
    {"id":"cajones-este","x":17,"y":0,"z":6.5,"zone":"Los Cajones"},
    {"id":"puerta-sur","x":-4,"y":0,"z":-8,"zone":"La Puerta"},
    {"id":"pasillo","x":9,"y":0,"z":-10,"zone":"Pasillo trasero"},
  ],
  pickups: [
    {"id":"casco-balcon","kind":"helmet","x":10.5,"y":"plataforma","z":-14.5,"zone":"El Balcón"},
    {"id":"escudo-cajones","kind":"shield","x":5.5,"y":0,"z":1.5,"zone":"Los Cajones"},
    {"id":"escudo-pasillo","kind":"shield","x":12.5,"y":0,"z":-2.5,"zone":"Pasillo trasero"},
    {"id":"escudo-largo","kind":"shield","x":-13.5,"y":0,"z":-0.5,"zone":"El Largo"},
    {"id":"escudo-puerta","kind":"shield","x":-2.5,"y":0,"z":-2.5,"zone":"La Puerta"},
    {"id":"vida-largo","kind":"health","x":-11.5,"y":0,"z":8.5,"zone":"El Largo"},
    {"id":"vida-cajones","kind":"health","x":18.5,"y":0,"z":4.5,"zone":"Los Cajones"},
    {"id":"vida-pasillo","kind":"health","x":3.5,"y":0,"z":-9.5,"zone":"Pasillo trasero"},
  ],
  routes: [
    {"id":"balcon-1","zone":"El Balcón","y":"plataforma","peek":false,"points":[{"id":"balcon-1-a","x":6.5,"z":-17.5},{"id":"balcon-1-b","x":9.5,"z":-18.5},{"id":"balcon-1-c","x":12.5,"z":-18.5},{"id":"balcon-1-d","x":10.5,"z":-14.5},{"id":"balcon-1-e","x":6.5,"z":-14.5},{"id":"balcon-1-f","x":3.5,"z":-14.5}]},
    {"id":"balcon-2","zone":"El Balcón","y":"plataforma","peek":false,"points":[{"id":"balcon-2-a","x":-9.5,"z":-16.5},{"id":"balcon-2-b","x":-6.5,"z":-16.5},{"id":"balcon-2-c","x":-3.5,"z":-17.5},{"id":"balcon-2-d","x":0.5,"z":-16.5},{"id":"balcon-2-e","x":-1.5,"z":-14.5},{"id":"balcon-2-f","x":-5.5,"z":-13.5}]},
    {"id":"balcon-3","zone":"El Balcón","y":"plataforma","peek":false,"points":[{"id":"balcon-3-a","x":-18.5,"z":-17.5},{"id":"balcon-3-b","x":-12.5,"z":-18.5},{"id":"balcon-3-c","x":-14.5,"z":-16.5},{"id":"balcon-3-d","x":-12.5,"z":-14.5},{"id":"balcon-3-e","x":-16.5,"z":-14.5}]},
    {"id":"balcon-4","zone":"El Balcón","y":"plataforma","peek":false,"points":[{"id":"balcon-4-a","x":15.5,"z":-18.5},{"id":"balcon-4-b","x":18.5,"z":-18.5},{"id":"balcon-4-c","x":18.5,"z":-12.5},{"id":"balcon-4-d","x":16.5,"z":-15.5}]},
    {"id":"cajones-1","zone":"Los Cajones","peek":true,"points":[{"id":"cajones-1-a","x":3.5,"z":-1.5},{"id":"cajones-1-b","x":6.5,"z":-1.5},{"id":"cajones-1-c","x":5.5,"z":1.5},{"id":"cajones-1-d","x":1.5,"z":1.5}]},
    {"id":"cajones-2","zone":"Los Cajones","peek":true,"points":[{"id":"cajones-2-a","x":15.5,"z":4.5},{"id":"cajones-2-b","x":18.5,"z":4.5},{"id":"cajones-2-c","x":18.5,"z":7.5},{"id":"cajones-2-d","x":15.5,"z":7.5}]},
    {"id":"cajones-3","zone":"Los Cajones","peek":true,"points":[{"id":"cajones-3-a","x":-5.5,"z":3.5},{"id":"cajones-3-b","x":-2.5,"z":4.5},{"id":"cajones-3-c","x":-0.5,"z":7.5},{"id":"cajones-3-d","x":-4.5,"z":6.5}]},
    {"id":"largo-1","zone":"El Largo","peek":false,"points":[{"id":"largo-1-a","x":-13.5,"z":10.5},{"id":"largo-1-b","x":-11.5,"z":5.5},{"id":"largo-1-c","x":-11.5,"z":8.5},{"id":"largo-1-d","x":-9.5,"z":12.5},{"id":"largo-1-e","x":-14.5,"z":13.5},{"id":"largo-1-f","x":-17.5,"z":13.5}]},
    {"id":"largo-2","zone":"El Largo","peek":false,"points":[{"id":"largo-2-a","x":-16.5,"z":-0.5},{"id":"largo-2-b","x":-18.5,"z":-3.5},{"id":"largo-2-c","x":-13.5,"z":-0.5},{"id":"largo-2-d","x":-10.5,"z":1.5},{"id":"largo-2-e","x":-18.5,"z":1.5}]},
    {"id":"pasillo-1","zone":"Pasillo trasero","peek":false,"points":[{"id":"pasillo-1-a","x":10.5,"z":-4.5},{"id":"pasillo-1-b","x":14.5,"z":-5.5},{"id":"pasillo-1-c","x":18.5,"z":-5.5},{"id":"pasillo-1-d","x":17.5,"z":-2.5},{"id":"pasillo-1-e","x":11.5,"z":0.5},{"id":"pasillo-1-f","x":12.5,"z":-2.5}]},
    {"id":"pasillo-2","zone":"Pasillo trasero","peek":false,"points":[{"id":"pasillo-2-a","x":0.5,"z":-9.5},{"id":"pasillo-2-b","x":3.5,"z":-9.5},{"id":"pasillo-2-c","x":6.5,"z":-10.5},{"id":"pasillo-2-d","x":9.5,"z":-9.5},{"id":"pasillo-2-e","x":7.5,"z":-7.5}]},
    {"id":"puerta-1","zone":"La Puerta","peek":true,"points":[{"id":"puerta-1-a","x":-4.5,"z":-9.5},{"id":"puerta-1-b","x":-2.5,"z":-5.5},{"id":"puerta-1-c","x":-2.5,"z":-2.5},{"id":"puerta-1-d","x":-4.5,"z":-0.5},{"id":"puerta-1-e","x":-5.5,"z":-4.5}]},
    {"id":"vestibulo-1","zone":"Vestíbulo","peek":false,"points":[{"id":"vestibulo-1-a","x":6.5,"z":14.5},{"id":"vestibulo-1-b","x":8,"z":12},{"id":"vestibulo-1-c","x":10.5,"z":8.5},{"id":"vestibulo-1-d","x":13,"z":8.5}]},
    {"id":"vestibulo-2","zone":"Vestíbulo","peek":false,"points":[{"id":"vestibulo-2-a","x":-3.5,"z":12},{"id":"vestibulo-2-b","x":-4.5,"z":14.5},{"id":"vestibulo-2-c","x":-7,"z":13},{"id":"vestibulo-2-d","x":-11.5,"z":14.5}]},
  ],
}
